name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3 # Pastikan versi v3 benar, cek marketplace jika perlu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          report_format: json
          report_path: gitleaks-report.json

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@v0 # Pastikan versi v0 benar, cek marketplace jika perlu
        with:
          image-ref: 'your-docker-repo/your-image-name:latest' # Ganti dengan nama image Anda
          severity: 'CRITICAL,HIGH'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '1'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4 # Perbarui ke versi v4
        if: always()
        with:
          name: trivy-report
          path: trivy-report.json
