name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config_path: .gitleaks.toml
          report_format: json
          report_path: gitleaks-report.json

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      - name: Build and Push Docker Image (Jika diperlukan)
        if: always()
        run: |
          docker build -t your-docker-repo/your-image-name:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} # Sesuaikan dengan registri Anda
          docker push your-docker-repo/your-image-name:latest

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@v0
        with:
          image-ref: 'your-docker-repo/your-image-name:latest' # Ganti dengan nama image Anda
          severity: 'CRITICAL,HIGH'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '1'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-report
          path: trivy-report.json
